import { Router } from "express";
import { authRoutes } from "./modules/auth/auth.routes.js";
import { userRoutes } from "./modules/users/user.routes.js";
import { patientRoutes } from "./modules/patients/patient.routes.js";
import { doctorRoutes } from "./modules/doctors/doctor.routes.js";
import { polyclinicRoutes } from "./modules/polyclinics/polyclinic.routes.js";
import { queueRoutes } from "./modules/queues/queue.routes.js";
import { visitRoutes } from "./modules/visits/visit.routes.js";
import { medicalRecordRoutes } from "./modules/medical-records/medical-record.routes.js";
import { prescriptionRoutes } from "./modules/prescriptions/prescription.routes.js";
import { medicineRoutes } from "./modules/medicines/medicine.routes.js";
import { paymentRoutes } from "./modules/payments/payment.routes.js";
import { reportRoutes } from "./modules/reports/report.routes.js";
import { nurseRoutes } from "./modules/nurses/nurse.routes.js";
import { staffRoutes } from "./modules/staff/staff.routes.js";
import { doctorScheduleRoutes } from "./modules/doctor-schedules/doctor-schedule.routes.js";
import { vitalSignRoutes } from "./modules/vital-signs/vital-sign.routes.js";
import { auditLogRoutes } from "./modules/audit-logs/audit-log.routes.js";
import { settingsRoutes } from "./modules/settings/settings.routes.js";
import { patientPortalRoutes } from "./modules/patient-portal/patient-portal.routes.js";
import { dashboardRoutes } from "./modules/dashboard/dashboard.routes.js";
import { notificationRoutes } from "./modules/notifications/notification.routes.js";
import { announcementRoutes } from "./modules/announcements/announcement.routes.js";
import { adminSystemRoutes } from "./modules/admin-system/admin-system.routes.js";

export const apiRoutes = Router();

apiRoutes.use("/auth", authRoutes);
apiRoutes.use("/dashboard", dashboardRoutes);
apiRoutes.use("/notifications", notificationRoutes);
apiRoutes.use("/announcements", announcementRoutes);
apiRoutes.use("/users", userRoutes);
apiRoutes.use("/patients", patientRoutes);
apiRoutes.use("/doctors", doctorRoutes);
apiRoutes.use("/nurses", nurseRoutes);
apiRoutes.use("/staff", staffRoutes);
apiRoutes.use("/polyclinics", polyclinicRoutes);
apiRoutes.use("/doctor-schedules", doctorScheduleRoutes);
apiRoutes.use("/queues", queueRoutes);
apiRoutes.use("/visits", visitRoutes);
apiRoutes.use("/vital-signs", vitalSignRoutes);
apiRoutes.use("/medical-records", medicalRecordRoutes);
apiRoutes.use("/prescriptions", prescriptionRoutes);
apiRoutes.use("/medicines", medicineRoutes);
  apiRoutes.use("/payments", paymentRoutes);

apiRoutes.use("/reports", reportRoutes);
apiRoutes.use("/audit-logs", auditLogRoutes);
apiRoutes.use("/settings", settingsRoutes);
apiRoutes.use("/admin-system", adminSystemRoutes);
apiRoutes.use("/patient-portal", patientPortalRoutes);
